import { useState, useEffect } from 'react';
import Head from 'next/head';
import Header from '@/components/navigation/Header';
import Footer from '@/components/navigation/Footer';
import Loader from '@/components/shared/Loader';
import {BsArrowUp} from 'react-icons/bs';

const Layout = ({children, title}) => {
  // const [loading, setLoading] = useState(true);
  const [showButton, setShowButton] = useState(false);

  const handleScrollToTop = () => {
    window.scrollTo({top: 0, behavior: 'smooth'});
  }

  // useEffect(() => {
  //   setTimeout(() => {
  //     setLoading(false);
  //   }, 2000);
  
  //   const body = document.querySelector('body');
  //   loading ? body.style.overflow = "hidden" : body.style.overflow = "visible";
  // }, [loading]);

  useEffect(() => {
    const handleScrollButtonVisibility = () => {
      window.pageYOffset > 300 ? setShowButton(true) : setShowButton(false);
    }

    window.addEventListener('scroll', handleScrollButtonVisibility);
    return () => {
      window.removeEventListener('scroll', handleScrollButtonVisibility);
    }
  }, []);

  return (
    <>
      {/* {loading && <Loader/>} */}
      <Head>
        <title>Medico | {title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
        {children}
      <Footer/>
      <button onClick={handleScrollToTop} type='button' className={`${showButton ? 'show' : ''} scrollTopButton`}><BsArrowUp/></button>
    </>
  )
}

export default Layout;