import Head from 'next/head';
import AllDoctors from '@/components/doctors/AllDoctors';

const Doctors = () => {
  return (
    <>
      <Head>
        <title>Medico | All Doctors</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mt-9 sm:mt-[55px] lg:mt-[67px] xl:mt-[83px]">
        <AllDoctors/>
      </main>
    </>
  )
}

export default Doctors;