import Head from 'next/head';
import { useRouter } from 'next/router';

const BlogDetails = () => {
  const router = useRouter();
  const blogId = router.query.blogId;

  return (
    <>
      <Head>
        <title>Medico | Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mt-9 sm:mt-[55px] lg:mt-[67px] xl:mt-[83px]">
        <p>Blog details {blogId}</p>
      </main>
    </>
  )
}

export default BlogDetails;