import AllBlogs from '@/components/blog/allBlogs/AllBlogs';
import PopularBlogs from '@/components/blog/popularBlogs/PopularBlogs';
import Head from 'next/head';
import React from 'react'

const Blog = () => {
  return (
    <>
      <Head>
        <title>Medico | Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mt-9 sm:mt-[55px] lg:mt-[67px] xl:mt-[83px]">
        <PopularBlogs/>
        <AllBlogs/>
      </main>
    </>
  )
}

export default Blog;