import AboutUs from '@/components/about/AboutUs';
import CertifiedDoctors from '@/components/about/CertifiedDoctors';
import History from '@/components/about/history/History';
import Service from '@/components/shared/service/Services';
import WhyUs from '@/components/shared/whyUs/WhyUs';
import Head from 'next/head';

const About = () => {
  return (
    <>
      <Head>
        <title>Medico | About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className="mt-9 sm:mt-[55px] lg:mt-[67px] xl:mt-[107px]">
        <AboutUs/>
        <Service/>
        <WhyUs/>
        <History/>
        <CertifiedDoctors/>
      </main>
    </>
  )
}

export default About;