import Banner from '@/components/home/Banner';
import Service from '@/components/shared/service/Service';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Medico | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mt-9 sm:mt-[55px] lg:mt-[67px] xl:mt-0">
        <Banner/>
        <Service/>
      </main>
    </>
  )
}
