import Banner from '@/components/home/Banner';
import Department from '@/components/home/departments/Department';
import DownloadApp from '@/components/home/DownloadApp';
import Service from '@/components/shared/service/Services';
import WhyUs from '@/components/shared/whyUs/WhyUs';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Medico | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mt-9 sm:mt-[55px] lg:mt-[67px] xl:mt-0">
        <Banner/>
        <Service/>
        <WhyUs/>
        <Department/>
        <DownloadApp/>
      </main>
    </>
  )
}
