import Pricing from "@/components/service/pricing/Pricing";
import ServiceIntro from "@/components/service/ServiceIntro";
import Video from "@/components/service/video/Video";
import Service from "@/components/shared/service/Service";
import Head from "next/head";

const service = () => {
  return (
    <>
      <Head>
        <title>Medico | Service</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mt-9 sm:mt-[55px] lg:mt-[67px] xl:mt-[83px]">
        {/* page title */}
        <div className="page-title pt-6 lg:pt-12 pb-3 lg:pb-6">
          <div className="container">
            <h2 className="text-2xl md:text-3xl lg:text-4xl xl:text-[40px] font-semibold text-primary-text text-center">Services</h2>
          </div>
        </div>

        <ServiceIntro/>
        <Service/>
        <Video/>
        <Pricing/>
      </main>
    </>
  )
}

export default service;