import Login from '@/components/authentication/Login';
import Head from 'next/head';

const Signin = () => {
  return (
    <>
      <Head>
        <title>Medico | Signin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Login/>
      </main>
    </>
  )
}

export default Signin