import Register from "@/components/authentication/Register";
import Head from "next/head";

const Signup = () => {
  return (
    <>
      <Head>
        <title>Medico | Signup</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Register/>
      </main>
    </>
  )
}

export default Signup;